/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[167] =
    {   0,
        0,    0,   27,   25,    1,    7,   25,   25,   25,   25,
       25,   25,    9,    2,    3,   10,   10,   10,   10,   10,
       10,   10,    6,    6,    1,    8,   10,   10,    3,    9,
        0,    0,    9,    0,    0,    0,    0,   10,    0,   10,
       10,    0,   10,   10,   10,   10,    0,    0,    0,    0,
        4,    5,    0,    0,   15,    0,    0,   12,   10,   10,
       10,   10,   10,   10,    0,    0,    9,   19,    0,    0,
        0,   16,   11,   10,   10,   10,   10,   10,   10,   10,
        0,    9,    0,    0,    0,   16,   17,   10,   10,   10,
       10,   10,   10,   13,    0,    0,    0,   17,   18,   10,

       10,   10,   10,   14,   10,    0,   18,   10,   10,   10,
       10,   10,   10,   10,   10,    0,   10,   10,   10,   10,
        0,   10,   10,   10,   10,    0,   10,   10,   10,   10,
       21,   10,   10,    0,   10,    0,   21,   10,   10,    0,
       10,   10,   10,    0,   10,   10,   24,   20,   10,   10,
        0,   20,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   23,   10,   22,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    5,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   15,   15,   15,   15,   15,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   26,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       27,    1,   28,    1,   29,    1,   30,   24,   31,   32,

       33,   24,   24,   24,   34,   24,   35,   36,   37,   38,
       39,   24,   24,   40,   41,   42,   24,   43,   24,   24,
       44,   24,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    3,    4,    5,    6,    7,    7,    8,
        9,    8,    7,   10,   11,   11,   11,   11,   11,   12,
       13,    1,   14,   15,   16,   15,   17,   14,   18,   15,
       15,   15,   16,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,    1,    1
    } ;

static yyconst short int yy_base[185] =
    {   0,
        0,    0,  329,  750,   45,  750,  299,  257,   26,  252,
       35,   47,   44,  750,   54,   60,   63,   51,   66,   69,
       72,   76,    0,  750,   78,  750,   79,   65,  750,   75,
      263,   94,  101,  235,  233,   74,    0,  116,  109,  124,
      115,  117,  133,  134,  140,  141,  240,   79,  221,  190,
      750,  750,  138,    0,  142,  192,  169,  750,  166,  172,
      175,  147,  184,  187,    0,  191,  205,  750,  205,  207,
        0,  218,  182,  129,  208,  226,  237,  242,  273,  243,
      104,  244,  274,  144,    0,  285,  287,  249,  304,  309,
      260,  315,  318,  750,    0,  307,  321,  147,  173,  319,

      261,  343,  348,  750,  351,  175,  750,  356,  355,  359,
      276,  364,  360,  367,  372,  264,  391,  395,  399,  400,
        0,  403,  406,  410,  429,  136,  433,  437,  438,  445,
       84,  442,  450,  381,  461,  110,  750,  475,  476,    0,
      479,  480,  484,   90,  485,  490,  232,  317,  491,  503,
       55,  750,  515,  518,  526,  527,  531,  532,  543,  539,
      536,  557,  408,  560,  442,  750,  574,  589,  602,  618,
      317,  636,  646,  661,  373,  221,  671,  686,  324,  696,
      336,  705,  719,  733
    } ;

static yyconst short int yy_def[185] =
    {   0,
      166,    1,  166,  166,  166,  166,  166,  167,  167,  166,
      166,  166,  166,  166,  166,  168,  168,  169,  168,  168,
      168,  168,  170,  166,  166,  166,  168,  169,  166,  171,
      172,  166,  166,  166,  166,  173,  174,  168,  166,  168,
      169,  166,  168,  168,  168,  168,  170,  175,  172,  166,
      166,  166,  173,  176,  177,  174,  166,  166,  168,  168,
      168,  168,  168,  168,  178,  166,  166,  166,  177,  177,
      179,  180,  174,  166,  168,  168,  168,  168,  168,  168,
      178,  166,  180,   83,  181,   83,  182,  168,  168,  168,
      168,  168,  168,  166,   86,  182,  182,   97,  166,  168,

      168,  168,  168,  166,  168,   97,  166,  168,  168,  168,
      168,  168,  168,  168,  168,   53,  168,  168,  168,  168,
      183,  168,  168,  168,  168,  183,  168,  168,  168,  168,
      166,  168,  168,   53,  168,  166,  166,  168,  168,  184,
      168,  168,  168,  184,  168,  168,   53,  166,  168,  168,
      166,  166,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,   53,  168,   53,    0,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166
    } ;

static yyconst short int yy_nxt[797] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    4,    9,   10,
        4,   10,   11,   12,   13,   13,   13,   13,   13,   14,
        4,   15,    4,   16,   16,   17,    4,    4,   18,   16,
       19,   16,   16,   20,   16,   16,   16,   16,   16,   21,
       16,   22,   16,   16,   23,   24,   25,   29,   25,   30,
       30,   30,   30,   30,   28,   31,   32,   37,   33,   33,
       33,   33,   33,   34,   36,   35,   37,   36,   29,   37,
       36,   37,   37,   36,  152,   37,   36,   42,   37,   25,
       36,   25,   37,   36,   53,   37,   39,  136,   66,   39,
       66,   42,   39,   53,   54,   39,   40,  148,   39,   48,

       54,   45,   39,  137,   43,   39,   44,   48,   30,   30,
       30,   30,   30,   32,   46,   33,   33,   33,   33,   33,
       36,   37,   37,   57,   57,   57,   57,   57,   36,  137,
       37,   57,   57,   57,   57,   57,   58,   36,   36,   37,
       37,   42,   39,  131,   36,   36,   37,   37,  166,   94,
       39,   36,   70,   37,  166,   42,   59,  166,   54,   39,
       39,   70,   71,  166,   54,   62,   39,   39,   71,  166,
       36,   60,   37,   39,  166,   61,   36,   63,   37,   36,
       78,   37,   64,   57,   57,   57,   57,   57,   36,   73,
       37,   36,   39,   37,   75,  107,   74,  166,   39,   73,

      107,   39,  166,   68,   77,   67,   67,   67,   67,   67,
       39,   76,   36,   39,   37,   70,   80,  166,   79,   82,
       82,   82,   82,   82,   70,   71,  166,   71,   84,   50,
       36,   71,   37,   71,   39,   69,   69,   84,   85,   88,
       86,   36,   53,   37,   85,   86,   36,   36,   37,   37,
       65,   53,   39,   36,   52,   37,   51,   89,   82,   82,
       82,   82,   82,   39,   36,   36,   37,   37,   39,   39,
      121,   50,   91,   29,   53,   39,   90,   36,   93,   37,
      116,  100,   37,   53,   84,   28,   39,   39,   92,   92,
       92,   92,  103,   84,   85,  166,   95,   97,  109,   39,

       85,   95,   39,   26,  166,  166,   97,  166,   36,   98,
       37,  166,  166,   36,   98,   37,  104,   97,  104,   36,
      151,   37,   36,   36,   37,   37,   97,   30,  166,  106,
       39,  166,   30,  166,  106,   39,  152,  101,   83,   83,
      166,   39,  102,  106,   39,   39,  166,   36,  106,   37,
       96,   96,   36,  105,   37,   36,  166,   37,  108,   36,
       36,   37,   37,   36,   36,   37,   37,  166,   36,   39,
       37,   36,  110,   37,   39,  166,   36,   39,   37,  166,
       67,   39,   39,   67,  114,   39,   39,  140,  111,  113,
       39,   53,  117,   39,  112,   36,  115,   37,   39,   36,

       53,   37,  118,   36,   36,   37,   37,   36,  119,   37,
       36,  166,   37,  120,   36,  166,   37,   39,   53,  166,
      122,   39,  166,  166,  123,   39,   39,   53,  125,   39,
      166,  124,   39,   36,  166,   37,   39,   36,  166,   37,
      127,   36,  134,   37,   37,  166,   36,  128,   37,   36,
      129,   37,   53,  166,   36,   39,   37,  166,  166,   39,
      130,   53,  166,   39,   39,   36,  166,   37,   39,  166,
      133,   39,  166,  166,  132,  138,   39,  135,  166,   36,
       36,   37,   37,   36,   36,   37,   37,   39,  147,   36,
       37,   37,  139,  166,   36,   36,   37,   37,  166,  166,

      141,   39,   39,  166,  166,   39,   39,   36,  143,   37,
       39,   39,  145,  166,  166,  142,   39,   39,  166,   36,
      153,   37,   36,  146,   37,  166,  150,  149,  166,   39,
       36,   36,   37,   37,  166,   36,   36,   37,   37,  154,
      163,   39,   37,   36,   39,   37,  166,   36,  166,   37,
      156,  166,   39,   39,  166,  166,  155,   39,   39,  157,
      166,   36,   39,   37,  165,   39,   37,  166,  158,   39,
      166,  160,  162,  159,  166,  161,  166,  166,  166,  166,
      166,  166,  166,   39,  166,  166,   39,  164,   27,   27,
      166,   27,   38,  166,   38,  166,  166,  166,  166,   38,

      166,  166,  166,   38,   38,   38,   38,   41,  166,  166,
      166,  166,   41,  166,  166,  166,   41,   41,   41,   41,
       47,  166,  166,   47,   47,   47,  166,   47,   47,  166,
      166,  166,   47,   47,  166,   47,   49,  166,   49,   49,
       49,   49,   49,   49,   49,  166,   49,   49,   49,   49,
       49,   49,   49,   49,   55,  166,  166,   55,   55,  166,
       55,   55,   55,   56,  166,   56,   56,   56,   56,   56,
       56,   56,  166,  166,  166,   56,   56,  166,   56,   72,
      166,  166,   72,   72,  166,   72,   72,   72,   81,  166,
      166,   81,   81,   81,   81,   81,   81,  166,  166,  166,

       81,   81,  166,   81,   87,  166,  166,   87,   87,   87,
       87,   87,   87,   99,  166,  166,   99,  166,   99,   99,
       99,  126,  166,  166,  166,  166,  166,  126,  166,  166,
      166,  166,  166,  126,  126,  144,  166,  166,  166,  166,
      166,  144,  166,  144,  166,  166,  166,  144,  144,    3,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166

    } ;

static yyconst short int yy_chk[797] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    9,    5,   11,
       11,   11,   11,   11,    9,   12,   13,   18,   13,   13,
       13,   13,   13,   15,   16,   15,   16,   17,   12,   17,
       19,   28,   19,   20,  151,   20,   21,   18,   21,   25,
       22,   25,   22,   27,   36,   27,   16,  131,   48,   17,
       48,   28,   19,   36,   36,   20,   17,  144,   21,   30,

       36,   21,   22,  131,   19,   27,   20,   30,   32,   32,
       32,   32,   32,   33,   22,   33,   33,   33,   33,   33,
       38,   41,   38,   39,   39,   39,   39,   39,   40,  136,
       40,   42,   42,   42,   42,   42,   39,   43,   44,   43,
       44,   41,   38,  126,   45,   46,   45,   46,   53,   81,
       40,   62,   55,   62,   84,   74,   40,   53,   53,   43,
       44,   55,   55,   84,   53,   44,   45,   46,   55,   98,
       59,   43,   59,   62,   98,   43,   60,   45,   60,   61,
       62,   61,   46,   57,   57,   57,   57,   57,   63,   73,
       63,   64,   59,   64,   59,   99,   57,  106,   60,   56,

       99,   61,  106,   50,   61,   66,   66,   66,   66,   66,
       63,   60,   75,   64,   75,   69,   64,   70,   63,   67,
       67,   67,   67,   67,   69,   69,   70,   70,   72,   49,
       76,   69,   76,   70,   75,  176,  176,   72,   72,   75,
       72,   77,  147,   77,   72,   72,   78,   80,   78,   80,
       47,  147,   76,   88,   35,   88,   34,   76,   82,   82,
       82,   82,   82,   77,   91,  101,   91,  101,   78,   80,
      116,   31,   78,   10,  116,   88,   77,   79,   80,   79,
      111,   88,  111,  116,   83,    8,   91,  101,   79,   79,
       79,   79,   91,   83,   83,   86,   83,   87,  101,   79,

       83,   83,  111,    7,   86,   86,   87,   86,   89,   87,
       89,   86,   86,   90,   87,   90,   92,   96,   92,   92,
      148,   92,   93,  100,   93,  100,   96,  171,    3,   96,
       89,   97,  171,    0,   96,   90,  148,   89,  179,  179,
       97,   92,   90,   97,   93,  100,    0,  102,   97,  102,
      181,  181,  103,   93,  103,  105,    0,  105,  100,  109,
      108,  109,  108,  110,  113,  110,  113,    0,  112,  102,
      112,  114,  102,  114,  103,    0,  115,  105,  115,    0,
      175,  109,  108,  175,  109,  110,  113,  134,  103,  108,
      112,  134,  112,  114,  105,  117,  110,  117,  115,  118,

      134,  118,  113,  119,  120,  119,  120,  122,  114,  122,
      123,    0,  123,  115,  124,    0,  124,  117,  163,    0,
      117,  118,    0,    0,  118,  119,  120,  163,  120,  122,
        0,  119,  123,  125,    0,  125,  124,  127,    0,  127,
      122,  128,  129,  128,  129,    0,  132,  123,  132,  130,
      124,  130,  165,    0,  133,  125,  133,    0,    0,  127,
      125,  165,    0,  128,  129,  135,    0,  135,  132,    0,
      128,  130,    0,    0,  127,  132,  133,  130,    0,  138,
      139,  138,  139,  141,  142,  141,  142,  135,  143,  145,
      143,  145,  133,    0,  146,  149,  146,  149,    0,    0,

      135,  138,  139,    0,    0,  141,  142,  150,  139,  150,
      143,  145,  141,    0,    0,  138,  146,  149,    0,  153,
      149,  153,  154,  142,  154,    0,  146,  145,    0,  150,
      155,  156,  155,  156,    0,  157,  158,  157,  158,  150,
      161,  153,  161,  160,  154,  160,    0,  159,    0,  159,
      154,    0,  155,  156,    0,    0,  153,  157,  158,  155,
        0,  162,  161,  162,  164,  160,  164,    0,  156,  159,
        0,  158,  160,  157,    0,  159,    0,    0,    0,    0,
        0,    0,    0,  162,    0,    0,  164,  162,  167,  167,
        0,  167,  168,    0,  168,    0,    0,    0,    0,  168,

        0,    0,    0,  168,  168,  168,  168,  169,    0,    0,
        0,    0,  169,    0,    0,    0,  169,  169,  169,  169,
      170,    0,    0,  170,  170,  170,    0,  170,  170,    0,
        0,    0,  170,  170,    0,  170,  172,    0,  172,  172,
      172,  172,  172,  172,  172,    0,  172,  172,  172,  172,
      172,  172,  172,  172,  173,    0,    0,  173,  173,    0,
      173,  173,  173,  174,    0,  174,  174,  174,  174,  174,
      174,  174,    0,    0,    0,  174,  174,    0,  174,  177,
        0,    0,  177,  177,    0,  177,  177,  177,  178,    0,
        0,  178,  178,  178,  178,  178,  178,    0,    0,    0,

      178,  178,    0,  178,  180,    0,    0,  180,  180,  180,
      180,  180,  180,  182,    0,    0,  182,    0,  182,  182,
      182,  183,    0,    0,    0,    0,    0,  183,    0,    0,
        0,    0,    0,  183,  183,  184,    0,    0,    0,    0,
        0,  184,    0,  184,    0,    0,    0,  184,  184,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grpp_lex.l"
#define INITIAL 0
#line 2 "grpp_lex.l"

/*
	File:		grpp_lex.l
	Description:	Lexical Analyzer for GRPP
	Author:		James Kent Blackburn
	Date:		Jan 2000

	Copyright (c) 1992-2000 
	By James Kent Blackburn
	All Rights Reserved
*/

#include <string.h>
#include <ctype.h>
#include "y.tab.h"

#define TRUE		1
#define FALSE		0

extern int	no_lines_in,no_lines_out,gr_debug;

int	n_dim,n_ind,
	grpp_okay = FALSE,
	grpp_block = FALSE,
	coord_flag = FALSE,
	index_flag = FALSE;

char	error_str[80] = "",
	coord_list[50] = "",
	upper_coord[25] = "",
	lower_coord[25] = "",
	index_list[50] = "",
	upper_index[25] = "",
	lower_index[25] = "",
	buffer[8192] = "";

void 	get_indices(char*),
	get_coordinates(char*),
	report_lex_error(char*),
	remove_derivative(char*, char*),
	expand_symmetry(char*);

int	is_vector(char*),
	is_index(char*),
	is_coord(char*);

#line 643 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 78 "grpp_lex.l"


#line 797 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 167 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 750 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%c",yytext[0]);
		    }
		  else
		    {
		     yylval.letter = yytext[0];
		     return SEMI;
		    }
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 95 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return EQ;
		    }
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 105 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,"( ");
		     return SYMEQ;
		    }
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 115 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,"-( ");
		     return SYMEQ;
		    }
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%c",yytext[0]);
		    }
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 130 "grpp_lex.l"
{ no_lines_in++;
		  yylval.letter = yytext[0];
		  return NL; 
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 134 "grpp_lex.l"
{ if (grpp_block)
		    {
		     grpp_block = FALSE;
		     strcpy(yylval.string,"/* Close GRPP Block */");
		    }
		  else
		    {
		     grpp_block = TRUE;
		     strcpy(yylval.string,"\n/* Open  GRPP Block */\n");
		     no_lines_out += 2;
		    }
		  return MARKER;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 147 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return NUMBER;
		    }
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 157 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return VARIABLE;
		    }
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 167 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return FUNCTION;
		    }
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 177 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return ARRAY;
		    }
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 187 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     if (is_vector(yytext))
		       {
			strcpy(yylval.string,yytext);
			return VECTOR;
		       }
		     else
		       {
			strcpy(error_str,"Vector definition Error");
			report_lex_error(error_str);
			return 0;			
		       }
		    }
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 206 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%s",yytext);
		    }
		  else
		    {
		     strcpy(yylval.string,yytext);
		     return TYPE;
		    }
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 216 "grpp_lex.l"
{ if ((is_index(yytext) == 1) && (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK1;
		    }
		  else if ((is_coord(yytext) == 1) && 
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     remove_dollars(buffer);
		     strcpy(yylval.string,buffer);
		     return VARIABLE;
		    }
		  else
		    {
		     strcpy(error_str,"Rank1 definition Error: ");
		     strcat(error_str,yytext);
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 238 "grpp_lex.l"
{ if ((is_index(yytext) == 2) && (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK2;
		    }
		  else if ((is_coord(yytext) == 2) && 
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     remove_dollars(buffer);
		     strcpy(yylval.string,buffer);
		     return VARIABLE;
		    }
		  else if ((is_index(yytext) == 1) && 
			   (is_coord(yytext) == 1) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK1;
		    }
		  else
		    {
		     strcpy(error_str,"Rank2 definition Error: ");
		     strcat(error_str,yytext);
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 268 "grpp_lex.l"
{ if ((is_index(yytext) == 3) && (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK3;
		    }
		  else if ((is_coord(yytext) == 3) && 
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     remove_dollars(buffer);
		     strcpy(yylval.string,buffer);
		     return VARIABLE;
		    }
		  else if ((is_index(yytext) == 2) && 
			   (is_coord(yytext) == 1) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK2;
		    }
		  else if ((is_index(yytext) == 1) && 
			   (is_coord(yytext) == 2) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK1;
		    }
		  else
		    {
		     strcpy(error_str,"Rank3 definition Error: ");
		     strcat(error_str,yytext);
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 306 "grpp_lex.l"
{ if ((is_index(yytext) == 4) && (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK4;
		    }
		  else if ((is_coord(yytext) == 4) && 
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     remove_dollars(buffer);
		     strcpy(yylval.string,buffer);
		     return VARIABLE;
		    }
		  else if ((is_index(yytext) == 3) && 
			   (is_coord(yytext) == 1) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK3;
		    }
		  else if ((is_index(yytext) == 2) && 
			   (is_coord(yytext) == 2) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK2;
		    }
		  else if ((is_index(yytext) == 1) && 
			   (is_coord(yytext) == 3) &&
			   (grpp_block && grpp_okay))
		    {
		     remove_derivative(yytext, buffer);
		     strcpy(yylval.string,buffer);
		     return RANK1;
		    }
		  else
		    {
		     strcpy(error_str,"Rank4 definition Error: ");
		     strcat(error_str,yytext);
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 352 "grpp_lex.l"
{ strcpy(yylval.string,yytext);
		  return COMMENT; 
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 355 "grpp_lex.l"
{ if (grpp_block)
		    {
		     get_coordinates(yytext);
		     coord_flag = TRUE;
		     if (index_flag) grpp_okay = TRUE;
		       return COORD;
		    }
		  else
		    {
		     strcpy(error_str,"coordinate$ Outside GRPP Block");
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 369 "grpp_lex.l"
{ if (grpp_block)
		    {
		     get_indices(yytext);
		     index_flag = TRUE;
		     if (coord_flag) grpp_okay = TRUE;
		       return INDICE;
		    }
		  else
		    {
		     strcpy(error_str,"indices$ Outside GRPP Block");
		     report_lex_error(error_str);
		     return 0;
		    }
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 383 "grpp_lex.l"
{ if (grpp_block) 
		    {
		     return ANTISYM;
		    }
		}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 388 "grpp_lex.l"
{ if (grpp_block) 
		    {
		     return COVDERIV;
		    }
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 393 "grpp_lex.l"
{ if (grpp_block) 
		    {
		     return LIEDERIV;
		    }
		}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 398 "grpp_lex.l"
{ if (!grpp_block) 
		    {
		     printf("%c",yytext[0]);
		    }
		  else
		    {
		     return yytext[0];
		    }
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 408 "grpp_lex.l"
ECHO;
	YY_BREAK
#line 1312 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 167 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 167 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 166);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 408 "grpp_lex.l"


/* integer function to check that vector has right dimensions */

int is_vector(char *vector)
{
 int i,length,n_components;

 n_components = 1;
 length = strlen(vector);
 for (i=0;i<length;i++)
    if (vector[i] == ',') n_components++;
 if (n_components == n_dim)
   return 1;
 else
   return 0;
}

/* integer function which test for good index values in tensor */

int is_index(char *tensor)
{
 int   n;
 char *dollar,tmp,*check;

 n = 0;
 dollar = (char *)index(tensor,'$');
 do {
     tmp = *(++dollar);
     if (isalpha(tmp))
       {
        check = (char *)index(index_list,tmp);
        if (check != '\0') n++;
	else check = (char *)index(coord_list,tmp);
       }
     else
       check = (char *)index(",;[]<>",tmp);
     }
 while ((tmp != '\0') && (check != '\0'));
 return n;
}

/* integer function which test for good coordinate values in tensor */

int is_coord(char *tensor)
{
 int   n;
 char *dollar,tmp,*check;

 n = 0;
 dollar = (char *)index(tensor,'$');
 do {
     tmp = *(++dollar);
     if (isalpha(tmp))
       {
        check = (char *)index(coord_list,tmp);
        if (check != '\0') n++;
	else check = (char *)index(index_list,tmp);
       }
     else
       check = (char *)index(",;[]<>",tmp);
     }
 while ((tmp != '\0') && (check != '\0'));
 return n;
}

/* void function which reads coordinates out of coordinate statement */

void get_coordinates(char *coord_state)
{
 char *open_par,*close_par,tmp;
 int i;

 open_par  = (char *)index(coord_state,'(');
 close_par = (char *)rindex(coord_state,')');
 n_dim = 0;
 i = 0;
 do {
     tmp = *(++open_par);
     if ((isalnum(tmp)) && (index(coord_list,tmp) == '\0'))
       {
        coord_list[i] = toupper(tmp);
        upper_coord[n_dim] = toupper(tmp);
        i++;
	coord_list[i] = tolower(tmp);
        lower_coord[n_dim] = tolower(tmp);
	i++;
        n_dim++;
       }
    }
 while (open_par != close_par);
 coord_list[i] = '\0';
 upper_coord[n_dim] = '\0';
 lower_coord[n_dim] = '\0';
}

/* void function which reads indices out of index statement */

void get_indices(char *index_state)
{
 char *open_par,*close_par,tmp;
 int i;

 open_par  = (char *)index(index_state,'(');
 close_par = (char *)rindex(index_state,')');
 n_ind = 0;
 i = 0;
 do {
     tmp = *(++open_par);
     if ((isalnum(tmp)) && (index(index_list,tmp) == '\0'))
       {
        index_list[i] = toupper(tmp);
        upper_index[n_ind] = toupper(tmp);
        i++;
	index_list[i] = tolower(tmp);
        lower_index[n_ind] = tolower(tmp);
	i++;
        n_ind++;
       }
    }
 while (open_par != close_par);
 index_list[i] = '\0';
 upper_index[n_ind] = '\0';
 lower_index[n_ind] = '\0';
}

/* remove derivative syntax (,;) from tensor string */

void remove_derivative(char *tensor, char *new_tensor)
{
 int	i,j,k,partial,covariant,length,order,ptr;
 char	clean[256] = "";

 length = strlen(tensor);
 j = ptr = partial = covariant = order = 0;
 for (i=0;i<length;i++)
    {
     if (tensor[i] == ',')
       partial = 1;
     else if (tensor[i] == ';')
       covariant = 1;
     else if (isalpha(tensor[i]))
       {
	clean[j] = tensor[i];
	j++;
	if (partial||covariant) order++;
       }
     else
       {
        if ((i==0) && (j == 0) && (tensor[i] == '*'))
          {
	   ptr = 1;
          }
        else if (tensor[i] == '$')
          { 
           clean[j] = '_'; j++;
	   for (k=(i+1);k<length;k++)
              {
	       if (isalpha(tensor[k]))
		 {
	          if (isupper(tensor[k])) 
		    clean[j] = 'C';
	          else
		    clean[j] = 'c';
	          j++;
		 }
              }
	   if (ptr)
	     {
	      clean[j] = ')';
	      j++;
	     }
	  }
	if (tensor[i] != '*') {
          clean[j] = tensor[i];
	  j++; }
       }
    }
 clean[j] = '\0';
 if (ptr) strcpy(new_tensor,"(*");
 else new_tensor[0] = '\0';
 switch (order)
       {
	case 0:
	  strcat(new_tensor,clean);
	break;
	case 1:
	  if (partial)
	    strcat(new_tensor,"_d_");
	  else if (covariant)
	    strcat(new_tensor,"_D_");
	  strcat(new_tensor,clean);
	break;
	case 2:
	  if (partial)
	    strcat(new_tensor,"_d2_");
	  else if (covariant)
	    strcat(new_tensor,"_D2_");
	  strcat(new_tensor,clean);
	break;
	case 3:
	  if (partial)
	    strcat(new_tensor,"_d3_");
	  else if (covariant)
	    strcat(new_tensor,"_D3_");
	  strcat(new_tensor,clean);
	break;
	case 4:
	  if (partial)
	    strcat(new_tensor,"_d4_");
	  else if (covariant)
	    strcat(new_tensor,"_D4_");
	  strcat(new_tensor,clean);
	break;
       }
 if (gr_debug)
   {
    fprintf(stderr,"TRACE: %s ->\n",tensor);
    fprintf(stderr,"       %s\n",new_tensor);
   }
 expand_symmetry(new_tensor);
}

/* expand any anti/symmetries */

void expand_symmetry(char* tensor)
{
 int	i,j,k,l,n,value,error,elements,sign,total,factor,nlist[5];
 char	*opn,list[5];
 char   ssign[5] = "";
 char   sfactor[5] = "";
 char	msg[80] = "";
 char   name[32] = "";
 char   expression[8192] = "";

 for (i=0;i<5;i++) list[i] = '\0';
 error = elements = sign = n = 0;
 if ((opn = (char *)index(tensor,'<')) != '\0')
   {
    if (index(tensor,'>') != '\0')
      {
       while (tensor[n] != '<')
	    {
	     name[n] = tensor[n];
	     n++;
	    }
       name[n] = '\0';
       sign = +1;
       while ((*opn != '>')&&(*opn != '\0'))
            {
	     if (isalpha(*opn))
	       {
		list[elements] = *opn;
		elements++;
	       }
	     opn++;
            }
       list[elements] = '\0';
       if ((elements < 2)||(elements > 4)) error = 1;
      }
    else
      {
       error = 1;
       strcpy(msg,"Error in symmetric tensor operator");
      }
   }
 else if ((opn = (char *)index(tensor,'[')) != '\0')
   {
    if (index(tensor,']') != '\0')
      {
       while (tensor[n] != '[')
	    {
	     name[n] = tensor[n];
	     n++;
	    }
       name[n] = '\0';
       sign = -1;
       while ((*opn != ']')&&(*opn != '\0'))
            {
	     if (isalpha(*opn))
	       {
		list[elements] = *opn;
		elements++;
	       }
	     opn++;
            }
       list[elements] = '\0';
       if ((elements < 2)||(elements > 4)) error = 1;
      }
    else
      {
       error = 1;
       strcpy(msg,"Error in anti-symmetric tensor operator");
      }
   }
 else if (index(tensor,'>') != '\0')
   {
    error = 1;
    strcpy(msg,"Error in symmetric tensor operator");
   }
 else if (index(tensor,']') != '\0')
   {
    error = 1;
    strcpy(msg,"Error in anti-symmetric tensor operator");
   }
 else return;
 if (error) report_lex_error(msg);
 if (sign != 0)
   {
    total = 0;
    strcpy(expression,"( ( ");
    switch (elements)
	  {
	   case 2:
	     factor = 2;
	     strcpy(sfactor,"2");
	     for (i=0;i<elements;i++)
		for (j=0;j<elements;j++)
		   {
		    if ( !(i==j) )
		      {
		       if (sign == -1)
			 {
		          nlist[0] = i; nlist[1] = j;
		          value = permutation_sort(elements,nlist);
		          if (value == 1)
			    strcpy(ssign," + ");
		          else
			    strcpy(ssign," - ");
			 }
		       else
			 strcpy(ssign," + ");
		       name[n] = list[i];
		       name[n+1] = list[j];
		       name[n+2] = '\0';
		       if ( (total > 0)&&(total < factor) )
			 strcat(expression,ssign);
		       strcat(expression,name);
		       total++;
		      }
		   }
	   break;
	   case 3:
	     factor = 6;
	     strcpy(sfactor,"6");
	     for (i=0;i<elements;i++)
		for (j=0;j<elements;j++)
		   for (k=0;k<elements;k++)
		      {
		       if ( !((i==j)||(i==k)||(j==k)) )
		         {
		          if (sign == -1)
			    {
		             nlist[0] = i; nlist[1] = j; nlist[2] = k;
		             value = permutation_sort(elements,nlist);
		             if (value == 1)
			       strcpy(ssign," + ");
		             else
			       strcpy(ssign," - ");
			    }
		          else
			    strcpy(ssign," + ");
		          name[n] = list[i];
		          name[n+1] = list[j];
		          name[n+2] = list[k];
		          name[n+3] = '\0';
		          if ( (total > 0)&&(total < factor) )
			    strcat(expression,ssign);
		          strcat(expression,name);
		          total++;
		         }
		      }
	   break;
	   case 4:
	     factor = 24;
	     strcpy(sfactor,"24");
	     for (i=0;i<elements;i++)
		for (j=0;j<elements;j++)
		   for (k=0;k<elements;k++)
		      for (l=0;l<elements;l++)
		         {
		          if ( !((i==j)||(i==k)||(i==l)||(j==k)||(j==l)||(k==l)) )
		            {
		             if (sign == -1)
			       {
		                nlist[0] = i; nlist[1] = j;
			        nlist[2] = k; nlist[3] = l;
		                value = permutation_sort(elements,nlist);
		                if (value == 1)
			          strcpy(ssign," + ");
		                else
			          strcpy(ssign," - ");
			       }
		             else
			       strcpy(ssign," + ");
		             name[n] = list[i];
		             name[n+1] = list[j];
		             name[n+2] = list[k];
		             name[n+3] = list[l];
		             name[n+4] = '\0';
		             if ( (total > 0)&&(total < factor) )
			       strcat(expression,ssign);
		             strcat(expression,name);
		             total++;
		            }
		         }
	   break;
	  }
    strcat(expression," )");
    strcat(expression," / ");
    strcat(expression,sfactor);
    strcat(expression," )");
    if ( (index(expression,'<') != '\0') || (index(expression,'<') != '\0') ||
         (index(expression,'[') != '\0') || (index(expression,']') != '\0') )
      {
       strcpy(msg,"Error in anti/symmetry operator: two occurrences?");
       report_lex_error(msg);
      }
    else
      {
       if (gr_debug)
	 {
	  fprintf(stderr,"TRACE: %s ->\n",tensor);
	  fprintf(stderr,"       %s\n",expression);
	 }
       strcpy(tensor,expression);
      }
   }
}

/* report a lexical error to the user */

void report_lex_error(char *error_str)
{
 fprintf(stderr,"Error in Lexical Analyzer:\n");
 fprintf(stderr,"*** %s ***\n",error_str);
 fprintf(stderr,"Error on input line: %d\n",no_lines_in);
}
